### ISSUE TITLE
Missing required properties: testRunId

### ISSUE THREAD

**Issue by nvkleban** [emulator-wtf/gradle-plugin#163]
After update from 0.17.0 to 0.18.1 pipeline fails with the next message.

```
> Task :app:test{REDACTED}DebugWithEmulatorWtf FAILED
01:20:39.766 INFO Creating run
java.lang.IllegalStateException: Http error 403: Invalid apiToken
	at y1.j.a(SourceFile:14)
	at E.L.b(SourceFile:1285)
	at Q.a.a(SourceFile:5)
	at k0.U.run(SourceFile:158)
	at k0.f0.p(SourceFile:20)
	at k0.e.a(SourceFile:23)
	at E.U.c(SourceFile:1)
	at c.o.a(SourceFile:9)
	at E1.b.b(SourceFile:158)
	at Q.a.a(SourceFile:5)
	at k0.U.run(SourceFile:158)
	at k0.f0.p(SourceFile:20)
	at k0.e.a(SourceFile:23)
	at E1.c.a(SourceFile:17)
	at E1.c.a(SourceFile:2)
	at emulatorwtf.cli.CliKt.main(SourceFile:18)
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:test{REDACTED}DebugWithEmulatorWtf'.
> A failure occurred while executing wtf.emulator.exec.EwWorkAction
> com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Missing required properties: testRunId
```

Can't find anything in documentation about this parameter.

**Comment by nvkleban** [comment]
On 0.17.0 403 error still persists, so probably some issue is on our side with tokens, I'll try to set a new one.
Can it expire in principle?

**Comment by madisp** [comment]
> On 0.17.0 403 error still persists, so probably some issue is on our side with tokens, I'll try to set a new one. Can it expire in principle?

Nope, we don't have any expiry for api tokens today. We'd be happy to help you debug this, but GitHub probably isn't the best place - can you send an email to support@emulator.wtf and we'll help you with the API token issue?

**Comment by nvkleban** [comment]
Ok, after downgrade and token update everything seems like worked fine for a while, until unfortunately not. I've wrote an email so closing this one.
