### ISSUE TITLE
Limited configuration cache support

### ISSUE THREAD

**Issue by PhilGlass** [emulator-wtf/gradle-plugin#18]
A number of the properties on `EwExtension` are incompatible with the configuration cache if they're set from a provider whose value isn't known at configuration time.

Here's one example:

```kotlin
emulatorwtf {
    // This works fine, because the value is known at configuration time.
    // But it also means the configuration cache is invalidated if the value of the Gradle property changes.
    baseOutputDir.set(
        findProperty("emulatorwtf.outputDir")?.let { layout.projectDirectory.dir(it.toString()) }
            ?: layout.buildDirectory.dir("emulatorwtf-out").get()
    )

    // So does this, for the same reason.
    val l = layout // Avoid capturing the implicit receiver.
    val unset = objects.property<String>()
    baseOutputDir.set(
        unset.map { l.projectDirectory.dir(it) }
            .orElse(layout.buildDirectory.dir("emulatorwtf-out"))
    )

    // This blows up when trying to store the configuration cache, because the value isn't known
    // at configuration time and the `map` lambda in the emulator.wtf plugin captures
    // an AGP variant object that can't be serialized.
    baseOutputDir.set(
        providers.gradleProperty("emulatorwtf.outputDir").map { l.projectDirectory.dir(it) }
            .orElse(layout.buildDirectory.dir("emulatorwtf-out"))
    )
}
```

and the offending line: https://github.com/emulator-wtf/gradle-plugin/blob/992cc22debdfb08b255a60da702fcbe786fcc0fd/src/main/java/wtf/emulator/EwPlugin.java#L361

I'm not sure, but I don't think the fix is straightforward (otherwise I would've opened a PR) - it may require migration to [the newer AGP APIs](https://developer.android.com/build/extend-agp#build-flow-extension-points), so you can safely access DSL/variant properties and be sure you're getting the finalized values?

**Comment by madisp** [comment]
thanks for the report, we'll take a look at this!

**Comment by madisp** [comment]
We worked around this by capturing the specific variables (e.g. `variantName`) instead of the full `variant` object. Release with the fix will go out soon.
